### ISSUE TITLE
проблемы с пробелами и кириллицей

### ISSUE THREAD

**Issue by misha99fr** [xRy0/OVKChat#2]
![изображение](https://github.com/xRy0/OVKChat/assets/83592338/23fbffac-28cc-4f17-b3fb-4ad1bc2c7289)
ну шо это блять такое

**Comment by xRy0** [comment]
@misha99fr Исправил, ишуй закрываю

**Comment by misha99fr** [comment]
еба спасибо сигма

**Comment by misha99fr** [comment]
а чо ты исправил я просто форк делал
